<a href="https://colab.research.google.com/github/Eunjane/J-sMathematical.github.io-/blob/main/R%20program%20lab_DataStructures.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Data Structures**

---

## R Data Types

Last time, we covered the 5 basic data types of the R programming language:
*   character (strings)
*   double (numeric)
*   integer
*   complex
*   logical (boolean, TRUE/FALSE)



## R Data Structures

Data types can be considered the most basic form of data. A collection of data types form what we call a **data structure**.

There are many data structures in R. Data structures we will commonly use in R are:
*  vectors
*  matrices
*  factors (categorical)
*  dataframes
*  lists

## Vectors


### Defined

A vector is a collection of elements that share the same data type. You can create a vector in R using the `c()` function. Think of the letter 'c' in `c()` as combine or concatenate.

The following is a numeric vector comprising a collection of numbers.

In [1]:
# This is a vector of numbers
my_vector <- c(1, 2, 3, 4)
my_vector

[1] 1 2 3 4

Similar to how we use the `typeof()` function to determine the R data type, we can use the `class()` function to determine the type of data structure or class.

In [2]:
# Use class to see the type of data structure
class(my_vector)

[1] "numeric"

In [3]:
# use typeof() to check the data type of elements within the vector
typeof(my_vector)

[1] "double"



<br>




The following is a vector comprising a collection of characters strings.

In [4]:
# This is a vector of character strings
my_vector <- c("hi", "hello", "hey there")
my_vector

[1] "hi"        "hello"     "hey there"

In [5]:
# Use class() to see the type of data structure
class(my_vector)

[1] "character"

In [6]:
# use typeof() to check the data type of elements within the vector
typeof(my_vector)

[1] "character"



<br>




Can we mix different data types in a vector? What do you think will happen in the following command?

In [7]:
# creating a vector of the number 1 and the logical TRUE
my_vector <- c(1, TRUE)
my_vector

typeof(my_vector)

[1] 1 1

[1] "double"



<br>




What happens when we combine a number with a string?

In [8]:
# first let's define a vector
my_vector <- c(1, 5)
my_vector

[1] 1 5

In [9]:
# check the class and data type
class(my_vector)
typeof(my_vector)

[1] "numeric"

[1] "double"

In [10]:
# add a character to the end of the vector 
my_vector <- c(my_vector, "hello there!")
my_vector

[1] "1"            "5"            "hello there!"

In [11]:
class(my_vector)
typeof(my_vector)

[1] "character"

[1] "character"

### Functions of Vectors

R has several built-in functions that will calculate metrics for us.

In [12]:
# define a vector
my_vector <- 1:5
my_vector

[1] 1 2 3 4 5

In [13]:
# length of my_vector
length(my_vector)

[1] 5

In [14]:
# sum of a vector
sum(my_vector)

[1] 15

In [15]:
# mean of my_vector
mean(my_vector)

sum(my_vector) / length(my_vector)

[1] 3

[1] 3

In [16]:
# variance
var(my_vector)

[1] 2.5



<br>




### Operations on Vectors

Operations are vectorized in R. This makes math very easy!

In [17]:
# create a vector from 1:100
my_vector <- 1:100
my_vector

[1]   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17  18
 [19]  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35  36
 [37]  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53  54
 [55]  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71  72
 [73]  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89  90
 [91]  91  92  93  94  95  96  97  98  99 100

In [18]:
# add 200 to each element
my_vector + 200

[1] 201 202 203 204 205 206 207 208 209 210 211 212 213 214 215 216 217 218
 [19] 219 220 221 222 223 224 225 226 227 228 229 230 231 232 233 234 235 236
 [37] 237 238 239 240 241 242 243 244 245 246 247 248 249 250 251 252 253 254
 [55] 255 256 257 258 259 260 261 262 263 264 265 266 267 268 269 270 271 272
 [73] 273 274 275 276 277 278 279 280 281 282 283 284 285 286 287 288 289 290
 [91] 291 292 293 294 295 296 297 298 299 300



<br>




What if we divide by 0?

In [19]:
my_vector / -0

[1] -Inf -Inf -Inf -Inf -Inf -Inf -Inf -Inf -Inf -Inf -Inf -Inf -Inf -Inf -Inf
 [16] -Inf -Inf -Inf -Inf -Inf -Inf -Inf -Inf -Inf -Inf -Inf -Inf -Inf -Inf -Inf
 [31] -Inf -Inf -Inf -Inf -Inf -Inf -Inf -Inf -Inf -Inf -Inf -Inf -Inf -Inf -Inf
 [46] -Inf -Inf -Inf -Inf -Inf -Inf -Inf -Inf -Inf -Inf -Inf -Inf -Inf -Inf -Inf
 [61] -Inf -Inf -Inf -Inf -Inf -Inf -Inf -Inf -Inf -Inf -Inf -Inf -Inf -Inf -Inf
 [76] -Inf -Inf -Inf -Inf -Inf -Inf -Inf -Inf -Inf -Inf -Inf -Inf -Inf -Inf -Inf
 [91] -Inf -Inf -Inf -Inf -Inf -Inf -Inf -Inf -Inf -Inf



<br>




We can add two vectors element by element.

In [20]:
# define two vectors
x <- 1:5
y <- 6:10

x
y

[1] 1 2 3 4 5

[1]  6  7  8  9 10

In [21]:
# add two vectors
x + y

[1]  7  9 11 13 15



<br>




This is where things get a little weird. What do you think happens in the following code cell?

In [22]:
x <- 1:5
y <- 1:10

x
y

[1] 1 2 3 4 5

[1]  1  2  3  4  5  6  7  8  9 10

In [23]:
x + y

length(x + y)

[1]  2  4  6  8 10  7  9 11 13 15

[1] 10



<br>




What if we set `y <- 1:11`?

In [24]:
x <- 1:5
y <- 1:11

x
y

[1] 1 2 3 4 5

[1]  1  2  3  4  5  6  7  8  9 10 11

In [25]:
# add vectors
x + y

Warning message in x + y:
“longer object length is not a multiple of shorter object length”


[1]  2  4  6  8 10  7  9 11 13 15 12

In [26]:
length(x + y)

Warning message in x + y:
“longer object length is not a multiple of shorter object length”


[1] 11



<br>




## Matrices

A matrix is a rectangular array of numbers. You may also think of matrices as vectors that are combined by row or column.

In R, you can create a matrix using the `matrix()` function.

In [27]:
my_matrix = matrix(5)
my_matrix

# the matrix above consists of a single number and is dimension 1x1

[,1]
[1,] 5

In [28]:
# check the type of data structure
class(my_matrix)

[1] "matrix" "array"

In [29]:
# check the data type of the matrix elements
typeof(my_matrix)

[1] "double"

In [30]:
# create a matrix with 3 rows and 2 columns
my_matrix <- matrix(c(1,2,3,4,5,6), nrow = 3, ncol = 2)
my_matrix

[,1] [,2]
[1,] 1    4   
[2,] 2    5   
[3,] 3    6

In [31]:
# create a matrix with 3 rows and 2 columns
my_matrix <- matrix(c(1,2,3,4,5,6), nrow = 3, ncol = 2, byrow=TRUE)
my_matrix

[,1] [,2]
[1,] 1    2   
[2,] 3    4   
[3,] 5    6



<br>




You can also combine vectors to create matrices. 

Combining vectors by row is called row concatenation using `rbind()`.

In [32]:
# create two vectors
vector1 <- c(1, 2, 3)
vector2 <- c(4, 5, 6)

class(vector1)

[1] "numeric"

In [33]:
# row bind the two vectors to create a matrix
new_matrix <- rbind(vector1, vector2)
new_matrix

[,1] [,2] [,3]
vector1 1    2    3   
vector2 4    5    6

In [34]:
# combining the two vectors alters the type of data structure
class(new_matrix)

[1] "matrix" "array"



<br>




You can also combine vectors by columns using the `cbind()` function.

In [35]:
# column bind the two vectors to create a matrix
new_matrix <- cbind(vector1, vector2)
new_matrix

vector1 vector2
[1,] 1       4      
[2,] 2       5      
[3,] 3       6



<br>




Operations and functions on matrices are similar to what we observed with vectors.

In [36]:
# mean of all elements in the matrix
mean(new_matrix)

[1] 3.5

In [37]:
# sum of all elements in the matrix
sum(new_matrix)

[1] 21

In [38]:
# matrix transpose
t(new_matrix)

[,1] [,2] [,3]
vector1 1    2    3   
vector2 4    5    6

In [39]:
# adding a matrix to a vector
vector1
new_matrix

[1] 1 2 3

vector1 vector2
[1,] 1       4      
[2,] 2       5      
[3,] 3       6

In [40]:
new_matrix + vector1

vector1 vector2
[1,] 2       5      
[2,] 4       7      
[3,] 6       9



<br>




## Factors

### Defined

* Factors are data structures used to categorize data into different "levels".
* They can store both strings and integers
* Factors are very useful for statistical modeling of categorical variables  (gender, ethnicity, etc.)

In [41]:
# let's define a few variables to understand factors and how they work
height <- c(132,151,162,139,166,147,122)
weight <- c(48, 49, 66, 53, 67, 52, 40)
gender <- c("male","male","female","female","male","female","male")

In [42]:
# class of the gender variable
class(gender)

[1] "character"



<br>




We can convert the `gender` variable into a factor using the `factor()` function

In [43]:
gender_factor <- factor(gender)
gender_factor

[1] male   male   female female male   female male  
Levels: female male



<br>




Unique categories of the factor variable are called levels in R.

We can observe the levels of the variable using the `levels()` function

In [44]:
levels(gender_factor)

[1] "female" "male"



<br>




Here, females are listed before males, but what if we wanted males listed before females?

Sometimes this is desired in a statistical analysis.

In [45]:
gender_factor <- factor(gender, levels = c("male", "female"))
gender_factor

[1] male   male   female female male   female male  
Levels: male female



<br>




Numeric variables can be converted to factors, but this doesn't make much sense. Why?

Here is an example anyway...


In [46]:
height_factor <- factor(height)
height_factor

[1] 132 151 162 139 166 147 122
Levels: 122 132 139 147 151 162 166



<br>




Can we add variables to a factor if the categories are "numbers"?

In [47]:
# adding 10 to factor
height_factor + 10

Warning message in Ops.factor(height_factor, 10):
“‘+’ not meaningful for factors”


[1] NA NA NA NA NA NA NA



<br>




How can we convert the factor back to a number? Let's try...

In [48]:
height_factor

[1] 132 151 162 139 166 147 122
Levels: 122 132 139 147 151 162 166

In [49]:
# convert the factor to numeric
as.numeric(height_factor)

[1] 2 5 6 3 7 4 1

CAREFUL!!! What happens in the above result?




<br>




If you want to convert the factor back to numeric using `as.character()` then `as.numeric()`

In [50]:
height_numeric <- as.numeric(as.character(height_factor))
height_numeric
class(height_numeric)

[1] 132 151 162 139 166 147 122

[1] "numeric"



<br>




* Note: Sometimes, categorical variables are coded with numbers (e.g., 1 = "Female", 2 = "Male")
* Be careful not to treat these variables as numerical, since they are categorical



<br>




## Dataframes

* Dataframes are possibly the most important data structure for this course
* If our data is not in the form of a dataframe, then we must convert the data to a dataframe
* Many of the algorithms in R take dataframes as input

* A dataframe is a special type of list where every element of the list has the same length
* We can combine vectors to form a dataframe using the `data.frame()` function

In [51]:
# variables
height <- c(132,151,162,139,166,147,122)
weight <- c(48, 49, 66, 53, 67, 52, 40)
gender <- c("male","male","female","female","male","female","male")

# create dataframe
dat <- data.frame(height, weight, gender)
dat

height weight gender
1 132    48     male  
2 151    49     male  
3 162    66     female
4 139    53     female
5 166    67     male  
6 147    52     female
7 122    40     male

In [52]:
# view the first few rows of the dataframe
head(dat, 3)

height weight gender
1 132    48     male  
2 151    49     male  
3 162    66     female

In [53]:
# view the last few rows of the dataframe
tail(dat, 3)

height weight gender
5 166    67     male  
6 147    52     female
7 122    40     male

In [54]:
# view the variable names of the dataframe
names(dat)

[1] "height" "weight" "gender"

In [55]:
# dimensions of the dataframe
dim(dat)

[1] 7 3

In [56]:
# number of rows
nrow(dat)

# number of columns
ncol(dat)

[1] 7

[1] 3

In [57]:
# description of each variable in the dataframe
str(dat)

'data.frame':	7 obs. of  3 variables:
 $ height: num  132 151 162 139 166 147 122
 $ weight: num  48 49 66 53 67 52 40
 $ gender: chr  "male" "male" "female" "female" ...




<br>




* We call/extract a variable (or column) from the dataframe using the `$` symbol
* Each column is a vector

In [58]:
# this calls the weight variable and multiplies by 2
dat$weight * 2

[1]  96  98 132 106 134 104  80

In [59]:
class(dat$weight)
typeof(dat$weight)

[1] "numeric"

[1] "double"



<br>




* We can store new variables using the `$` symbol
* You must be careful not to overwrite your original data!

In [60]:
# store weight * 2 as twice_weight
dat$twice_weight <- dat$weight * 2

head(dat)

height weight gender twice_weight
1 132    48     male    96         
2 151    49     male    98         
3 162    66     female 132         
4 139    53     female 106         
5 166    67     male   134         
6 147    52     female 104



<br>




## List

* The list class allows you to store multiple data structures in a single variable
* This is useful if you have multiple data structures associated with a single object
* For example, a patient may have demographic data, a CT image of their lungs, and genomic data

* Lists are created using the `list()` function

In [61]:
# create a dataframe
height <- c(132,151,162,139,166,147,122)
weight <- c(48, 49, 66, 53, 67, 52, 40)
gender <- c("male","male","female","female","male","female","male")
dat <- data.frame(height, weight, gender)

# create a vector
vec <- sample(1:100, 5)

# create a matrix
mat <- matrix(1:10, ncol=2)

# create a factor
fac <- factor(c("0-20 hours", "21-40 hours", 
                ">40 hours", "0-20 hours", ">40 hours"))

In [62]:
# combine these into a list
my_list <- list(my_data = dat, my_vector = vec, my_matrix = mat, my_factor = fac)
my_list

$my_data
  height weight gender
1    132     48   male
2    151     49   male
3    162     66 female
4    139     53 female
5    166     67   male
6    147     52 female
7    122     40   male

$my_vector
[1] 66  8  9 22 87

$my_matrix
     [,1] [,2]
[1,]    1    6
[2,]    2    7
[3,]    3    8
[4,]    4    9
[5,]    5   10

$my_factor
[1] 0-20 hours  21-40 hours >40 hours   0-20 hours  >40 hours  
Levels: >40 hours 0-20 hours 21-40 hours



<br>




* Notice that each of the elements of the list has a name (e.g., `$my_factor`)
* You can observe the names of the list elements using the `names()` function

In [63]:
names(my_list)

[1] "my_data"   "my_vector" "my_matrix" "my_factor"



<br>




* You can call elements of the list by their name

In [64]:
my_list$my_data

height weight gender
1 132    48     male  
2 151    49     male  
3 162    66     female
4 139    53     female
5 166    67     male  
6 147    52     female
7 122    40     male

In [65]:
my_list$my_matrix

[,1] [,2]
[1,] 1     6  
[2,] 2     7  
[3,] 3     8  
[4,] 4     9  
[5,] 5    10